apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hvozcpboe-nodejs
  janus-idp.io/tekton: hvozcpboe-nodejs
  backstage.io/kubernetes-id: hvozcpboe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hvozcpboe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
